services:
  - type: worker
    name: riya-music-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: API_ID
        value: "24845544"
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: OWNER_ID
        value: "5658759638"
      - key: LOGGER_ID
        value: "-1003311004575"
      - key: API_URL
        value: "https://apex.spacebilla01.workers.dev"
      - key: DOCKER
        value: "1"
